### PR TITLE
Gamepadui and Vector.h float bug fixed

### PR DESCRIPTION
**Pull request by HH45137**

### CODE REVIEW

**Comment by stephen-cusi** [comment]
OK thanks💪🏼💪🏼💪🏼

**Comment by nn-firc** [comment]
lgtm

**Comment by HH45137** [comment]
> lgtm

Yes, this is shit

**Comment by stephen-cusi** [comment]
> lgtm

You are **right**

**Comment by stephen-cusi** [comment]
When the actual machine is suitable, I will merge this more critical request at that time

**Pull request merged**
